# -*- coding: utf-8 -*-
"""Demodummy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFqbptYQnP0hD3ONHODiLZ3BROU9y-K6
"""

!pip install python-docx wordcloud matplotlib

from google.colab import files

uploaded = files.upload()
# Choose your file, e.g., sample.docx

from docx import Document

# Load the uploaded file
doc = Document("Introduction.docx")

# Extract text from all paragraphs
text = " ".join([para.text for para in doc.paragraphs])
print(text[:500])  # Preview first 500 characters

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Create WordCloud object
wordcloud = WordCloud(width=800, height=400, background_color="white").generate(text)

# Display the WordCloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
from docx import Document

# Load the Word file
doc = Document("Introduction.docx")

# Extract text from all paragraphs
text = " ".join([para.text for para in doc.paragraphs])

# Define stopwords
stopwords = set(STOPWORDS)
# You can add custom words to ignore
stopwords.update(["resume", "curriculum", "vitae","includes","include","became","check","year"])  # example

# Create WordCloud with stopwords
wordcloud = WordCloud(width=800, height=400,
                      background_color="white",
                      stopwords=stopwords).generate(text)

# Display Word Cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()